spring.application.name=logistica
spring.datasource.url=jdbc:postgresql://localhost:5432/estoque_banco
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver